# Generated by Django 5.1.1 on 2024-12-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='privatechat.privatechatroom'),
        ),
    ]
